# Generated by Django 3.1.4 on 2021-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210312_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(default='25BBCD', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnail-default.jpg', upload_to='media'),
        ),
    ]
